/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const BookRequest = IDL.Record({
  'destination' : IDL.Text,
  'date' : IDL.Text,
  'name' : IDL.Text,
  'specialRequests' : IDL.Text,
  'time' : IDL.Text,
  'vehiclePreference' : IDL.Text,
  'passengers' : IDL.Nat,
  'email' : IDL.Text,
  'phone' : IDL.Text,
  'pickupLocation' : IDL.Text,
});
export const BookingStatus = IDL.Variant({
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const Time = IDL.Int;
export const Booking = IDL.Record({
  'status' : BookingStatus,
  'destination' : IDL.Text,
  'date' : IDL.Text,
  'name' : IDL.Text,
  'specialRequests' : IDL.Text,
  'time' : IDL.Text,
  'vehiclePreference' : IDL.Text,
  'passengers' : IDL.Nat,
  'email' : IDL.Text,
  'timestamp' : Time,
  'phone' : IDL.Text,
  'pickupLocation' : IDL.Text,
});
export const ContactRequest = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
});

export const idlService = IDL.Service({
  'createBooking' : IDL.Func([BookRequest], [IDL.Nat], []),
  'createContactRequest' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'getAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getAllContactRequests' : IDL.Func([], [IDL.Vec(ContactRequest)], ['query']),
  'getBooking' : IDL.Func([IDL.Nat], [Booking], ['query']),
  'getContactRequest' : IDL.Func([IDL.Nat], [ContactRequest], ['query']),
  'updateBookingStatus' : IDL.Func([IDL.Nat, BookingStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const BookRequest = IDL.Record({
    'destination' : IDL.Text,
    'date' : IDL.Text,
    'name' : IDL.Text,
    'specialRequests' : IDL.Text,
    'time' : IDL.Text,
    'vehiclePreference' : IDL.Text,
    'passengers' : IDL.Nat,
    'email' : IDL.Text,
    'phone' : IDL.Text,
    'pickupLocation' : IDL.Text,
  });
  const BookingStatus = IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const Time = IDL.Int;
  const Booking = IDL.Record({
    'status' : BookingStatus,
    'destination' : IDL.Text,
    'date' : IDL.Text,
    'name' : IDL.Text,
    'specialRequests' : IDL.Text,
    'time' : IDL.Text,
    'vehiclePreference' : IDL.Text,
    'passengers' : IDL.Nat,
    'email' : IDL.Text,
    'timestamp' : Time,
    'phone' : IDL.Text,
    'pickupLocation' : IDL.Text,
  });
  const ContactRequest = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
  });
  
  return IDL.Service({
    'createBooking' : IDL.Func([BookRequest], [IDL.Nat], []),
    'createContactRequest' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'getAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getAllContactRequests' : IDL.Func(
        [],
        [IDL.Vec(ContactRequest)],
        ['query'],
      ),
    'getBooking' : IDL.Func([IDL.Nat], [Booking], ['query']),
    'getContactRequest' : IDL.Func([IDL.Nat], [ContactRequest], ['query']),
    'updateBookingStatus' : IDL.Func([IDL.Nat, BookingStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };