/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BookRequest {
  'destination' : string,
  'date' : string,
  'name' : string,
  'specialRequests' : string,
  'time' : string,
  'vehiclePreference' : string,
  'passengers' : bigint,
  'email' : string,
  'phone' : string,
  'pickupLocation' : string,
}
export interface Booking {
  'status' : BookingStatus,
  'destination' : string,
  'date' : string,
  'name' : string,
  'specialRequests' : string,
  'time' : string,
  'vehiclePreference' : string,
  'passengers' : bigint,
  'email' : string,
  'timestamp' : Time,
  'phone' : string,
  'pickupLocation' : string,
}
export type BookingStatus = { 'pending' : null } |
  { 'completed' : null } |
  { 'confirmed' : null };
export interface ContactRequest {
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : Time,
}
export type Time = bigint;
export interface _SERVICE {
  'createBooking' : ActorMethod<[BookRequest], bigint>,
  'createContactRequest' : ActorMethod<[string, string, string], bigint>,
  'getAllBookings' : ActorMethod<[], Array<Booking>>,
  'getAllContactRequests' : ActorMethod<[], Array<ContactRequest>>,
  'getBooking' : ActorMethod<[bigint], Booking>,
  'getContactRequest' : ActorMethod<[bigint], ContactRequest>,
  'updateBookingStatus' : ActorMethod<[bigint, BookingStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];